### ISSUE TITLE
deploy-node-1 Container always restart

### ISSUE THREAD

**Issue by hustwk** [ritual-net/infernet-node#17]
While running ritual validator node, the container always restart.

## Docker config
```
services:
  node:
    image: ritualnetwork/infernet-node:latest
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./config.json:/app/config.json
      - node-logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    depends_on:
      - redis
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1m
```

## Detail logs:

```
2024-03-27 18:18:24 [info     ] Initialized ChainProcessor                         [chain.processor]
2024-03-27 18:18:24 [info     ] Initialized ChainListener                          [chain.listener]
2024-03-27 18:18:24 [info     ] Initialized RESTServer                             [server.rest] port=4000
2024-03-27 18:18:24 [info     ] Running node lifecycle setup                       [__main__]
2024-03-27 18:18:24 [info     ] Pulling images, this may take a while...           [orchestration.docker]
2024-03-27 18:18:24 [info     ] Pulling image ritualnetwork/hello-world-infernet:latest... [orchestration.docker]
2024-03-27 18:18:24 [info     ] Pulling image ritualnetwork/infernet-anvil:0.0.0... [orchestration.docker]
2024-03-27 18:18:25 [info     ] Successfully pulled image ritualnetwork/hello-world-infernet:latest [orchestration.docker]
2024-03-27 18:18:25 [info     ] Successfully pulled image ritualnetwork/infernet-anvil:0.0.0 [orchestration.docker]
2024-03-27 18:18:25 [info     ] Container already running: hello-world             [orchestration.docker]
2024-03-27 18:18:25 [info     ] Container already running: anvil-node              [orchestration.docker]
2024-03-27 18:18:25 [info     ] Waiting for container startup                      [orchestration.docker] seconds=1.0
2024-03-27 18:18:26 [info     ] Container manager setup complete                   [orchestration.docker] running_containers=['hello-world', 'anvil-node']
2024-03-27 18:18:26 [info     ] Started snapshot sync                              [chain.listener] head=12387079 behind=0
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/web3/contract/utils.py", line 319, in async_call_contract_function
    output_data = async_w3.codec.decode(output_types, return_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_abi/codec.py", line 162, in decode
    return cast(Tuple[Any, ...], decoder(stream))
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 131, in __call__
    return self.decode(stream)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_utils/functional.py", line 47, in inner
    return callback(fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 224, in decode
    self.validate_pointers(stream)
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 218, in validate_pointers
    decoder(stream)
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 131, in __call__
    return self.decode(stream)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 250, in decode
    raw_data = self.read_data_from_stream(stream)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_abi/decoding.py", line 389, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes, only got 0 bytes.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/main.py", line 192, in <module>
    lifecycle_main()
  File "/app/src/main.py", line 178, in lifecycle_main
    loop.run_until_complete(lifecycle_setup())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 119, in lifecycle_setup
    await resource.setup()
  File "/app/src/chain/listener.py", line 339, in setup
    await self._snapshot_sync(cast(BlockNumber, head_block))
  File "/app/src/chain/listener.py", line 174, in _snapshot_sync
    head_id = await self._coordinator.get_head_subscription_id(head_block)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/chain/coordinator.py", line 416, in get_head_subscription_id
    await self._contract.functions.id().call(block_identifier=block_number),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/contract/async_contract.py", line 307, in call
    return await async_call_contract_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/contract/utils.py", line 337, in async_call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```

**Comment by kbakdev** [comment]
I think it is intended behaviour

**Comment by whonion** [comment]
nano ~/infernet-container-starter/deploy/docker-compose.yaml
```yml
services:
  node:
    image: ritualnetwork/infernet-node:1.2.0
```
