### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by 720x** [ritual-net/infernet-node#24]
node-1       | Traceback (most recent call last):
node-1       |   File "/app/src/orchestration/docker.py", line 210, in setup
node-1       |     await self._pull_images()
node-1       |   File "/app/src/orchestration/docker.py", line 363, in _pull_images
node-1       |     raise RuntimeError("Could not pull all images.")
node-1       | RuntimeError: Could not pull all images.
node-1       |
node-1       | During handling of the above exception, another exception occurred:
node-1       |
node-1       | Traceback (most recent call last):
node-1       |   File "/app/src/main.py", line 312, in <module>
node-1       |     node.lifecycle_main()
node-1       |   File "/app/src/main.py", line 296, in lifecycle_main
node-1       |     loop.run_until_complete(self._lifecycle_setup())
node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
node-1       |     return future.result()
node-1       |            ^^^^^^^^^^^^^^^
node-1       |   File "/app/src/main.py", line 221, in _lifecycle_setup
node-1       |     await asyncio.gather(*(resource.setup() for resource in self._tasks))
node-1       |   File "/app/src/orchestration/docker.py", line 232, in setup
node-1       |     raise RuntimeError(
node-1       | RuntimeError: Container manager setup failed. Check logs for details.

**Comment by Favy217** [comment]
you're getting the error because the v1.1.0 release of the registry address is buggy. use the v1.0.0 base mainnet registry address while editing your config file.
