### ISSUE TITLE
Node crashes after initialization

### ISSUE THREAD

**Issue by Stoicx-ai** [ritual-net/infernet-node#6]
Hi, 

I`ve managed to set up the node and can even register it on the chain but after around 15 mins after it has ran through all 2217 subscription IDs the container crashes with this error:

node-1       | 2024-02-22 20:34:15 [info     ] Ignored subscription creation                      [chain.listener] id=2216 err=Container not supported
node-1       | 2024-02-22 20:34:15 [info     ] Ignored subscription creation                      [chain.listener] id=2217 err=Container not supported
node-1       | 2024-02-22 20:34:15 [info     ] Finished snapshot sync                             [chain.listener] new_head=10921813
node-1       | 2024-02-22 20:34:17 [info     ] Running node lifecycle                             [__main__] 
node-1       | 2024-02-22 20:34:17 [info     ] Started ChainListener lifecycle                    [chain.listener] last_synced=10921813
node-1       | 2024-02-22 20:34:17 [info     ] Serving REST webserver                             [server.rest] addr=0.0.0.0 port=4000
node-1       | /usr/local/lib/python3.11/site-packages/structlog/stdlib.py:1062: UserWarning: Remove `format_exc_info` from your processor chain if you want pretty exceptions.
node-1       |   ed = p(logger, meth_name, ed)
node-1       | --- Logging error ---
node-1       | Traceback (most recent call last):
node-1       |   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
node-1       |     msg = self.format(record)
node-1       |           ^^^^^^^^^^^^^^^^^^^
node-1       |   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
node-1       |     return fmt.format(record)
node-1       |            ^^^^^^^^^^^^^^^^^^
node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 1062, in format
node-1       |     ed = p(logger, meth_name, ed)
node-1       |          ^^^^^^^^^^^^^^^^^^^^^^^^
node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/dev.py", line 513, in __call__
node-1       |     sio.write("\n" + exc)
node-1       |               ~~~~~^~~~~
node-1       | TypeError: can only concatenate str (not "ValueError") to str
node-1       | Call stack:
node-1       |   File "/app/src/main.py", line 183, in <module>
node-1       |     lifecycle_main()
node-1       |   File "/app/src/main.py", line 176, in lifecycle_main
node-1       |     loop.run_until_complete(lifecycle_run())
node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
node-1       |     self.run_forever()
node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
node-1       |     self._run_once()
node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
node-1       |     handle._run()
node-1       |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
node-1       |     self._context.run(self._callback, *self._args)
node-1       |   File "/app/src/main.py", line 125, in lifecycle_run
node-1       |     log.error("Task exception", exception=task.exception())
node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 200, in error
node-1       |     return self._proxy_to_logger("error", event, *args, **kw)
node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 247, in _proxy_to_logger
node-1       |     return super()._proxy_to_logger(method_name, event=event, **event_kw)
node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/_base.py", line 223, in _proxy_to_logger
node-1       |     return getattr(self._logger, method_name)(*args, **kw)
node-1       | Message: {'exception': ValueError({'code': -32000, 'message': 'filter not found'}), 'event': 'Task exception', 'level': 'error', 'logger': '__main__', 'timestamp': '2024-02-22 20:34:17'}
node-1       | Arguments: ()
node-1       | 2024-02-22 20:34:18 [info     ] Exited main process                                [__main__] 
node-1 exited with code 0

Any assistance would be much appreciated :)

**Comment by Stoicx-ai** [comment]
my RPC URL was the issue.
