### ISSUE TITLE
Node crashes on RPC error response (Quicknode)

### ISSUE THREAD

**Issue by crypt1d** [ritual-net/infernet-node#7]
If I use Quicknode as a RPC for the node (base chain), it will crash once it finishes syncing up with the chain:

```
deploy-node-1       | 2024-02-24 02:39:14 [info     ] Sent tx                                            [chain.processor] id=2217 interval=1 delegated=False tx_hash=******
deploy-node-1       | 2024-02-24 02:39:14 [info     ] Sent tx                                            [chain.processor] id=2218 interval=1 delegated=False tx_hash=****
deploy-node-1       | /usr/local/lib/python3.11/site-packages/structlog/stdlib.py:1062: UserWarning: Remove `format_exc_info` from your processor chain if you want pretty exceptions.
deploy-node-1       |   ed = p(logger, meth_name, ed)
deploy-node-1       | --- Logging error ---
deploy-node-1       | Traceback (most recent call last):
deploy-node-1       |   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
deploy-node-1       |     msg = self.format(record)
deploy-node-1       |           ^^^^^^^^^^^^^^^^^^^
deploy-node-1       |   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
deploy-node-1       |     return fmt.format(record)
deploy-node-1       |            ^^^^^^^^^^^^^^^^^^
deploy-node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 1062, in format
deploy-node-1       |     ed = p(logger, meth_name, ed)
deploy-node-1       |          ^^^^^^^^^^^^^^^^^^^^^^^^
deploy-node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/dev.py", line 513, in __call__
deploy-node-1       |     sio.write("\n" + exc)
deploy-node-1       |               ~~~~~^~~~~
deploy-node-1       | TypeError: can only concatenate str (not "ClientResponseError") to str
deploy-node-1       | Call stack:
deploy-node-1       |   File "/app/src/main.py", line 179, in <module>
deploy-node-1       |     lifecycle_main()
deploy-node-1       |   File "/app/src/main.py", line 172, in lifecycle_main
deploy-node-1       |     loop.run_until_complete(lifecycle_run())
deploy-node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
deploy-node-1       |     self.run_forever()
deploy-node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
deploy-node-1       |     self._run_once()
deploy-node-1       |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
deploy-node-1       |     handle._run()
deploy-node-1       |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
deploy-node-1       |     self._context.run(self._callback, *self._args)
deploy-node-1       |   File "/app/src/main.py", line 123, in lifecycle_run
deploy-node-1       |     log.error("Task exception", exception=task.exception())
deploy-node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 200, in error
deploy-node-1       |     return self._proxy_to_logger("error", event, *args, **kw)
deploy-node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/stdlib.py", line 247, in _proxy_to_logger
deploy-node-1       |     return super()._proxy_to_logger(method_name, event=event, **event_kw)
deploy-node-1       |   File "/usr/local/lib/python3.11/site-packages/structlog/_base.py", line 223, in _proxy_to_logger
deploy-node-1       |     return getattr(self._logger, method_name)(*args, **kw)
deploy-node-1       | Message: {'exception': ClientResponseError(RequestInfo(url=URL('https://dry-prettiest-hexagon.base-mainnet.quiknode.pro/****'), method='POST', headers=<CIMultiDictProxy('Host': 'dry-prettiest-hexagon.base-mainnet.quiknode.pro', 'Content-Type': 'application/json', 'User-Agent': "web3.py/6.11.0/<class 'web3.providers.async_rpc.AsyncHTTPProvider'>", 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '402')>, real_url=URL('https://dry-prettiest-hexagon.base-mainnet.quiknode.pro/*****')), (), status=413, message='Request Entity Too Large', headers=<CIMultiDictProxy('Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type,Authorization,User-Agent', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Origin': '', 'Content-Type': 'application/json', 'Vary': 'Accept-Encoding', 'X-Node-Id': 'base_base-mainnet_fra', 'X-Ratelimit-Limit': '1000000, 1000000;w=86400', 'X-Ratelimit-Remaining': '967152', 'X-Ratelimit-Reset': '81875', 'Date': 'Sat, 24 Feb 2024 02:39:14 GMT', 'Content-Length': '168')>), 'event': 'Task exception', 'level': 'error', 'logger': '__main__', 'timestamp': '2024-02-24 02:39:14'}
```

Error code suggests that the request body is too large for Quicknode to handle:
https://support.quicknode.com/hc/en-us/articles/20626358903185-Understanding-the-413-Request-Entity-Too-Large-Error

Seems to work fine with Alchemy which likely doesn't rate limit in the same way.

**Comment by Stoicx-ai** [comment]
hi crypt1d,

which endpoint are you using that is currently working?

**Comment by crypt1d** [comment]
> hi crypt1d,
> 
> which endpoint are you using that is currently working?

Alchemy seems to work just fine.

**Comment by stelios-ritual** [comment]
This is a known issue with some RPC providers. Alchemy seems to work for most people. Thanks for flagging!
